# FIRST_HALF) 아이디, 맛, 주문량
# ICECREAM_INFO) 맛, 재료타입
# 재료타입과 총주문량 오름차순
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN ICECREAM_INFO I 
ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE 
HAVING SUM(TOTAL_ORDER)
ORDER BY TOTAL_ORDER ASC