# 디벨로퍼에서 파이썬이나 C# 인 사람만 조회
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "Python") 
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = "C#") 
ORDER BY ID ASC;