# 피시인포) 잡은 물고기 정보
# 피시네임인포) 물고기에 대한 정보
# FISH_TYPE 조인
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'