# 연도별 대장균의 크기 비교, MAX를 찾기.
# 편차는 MAX - SIZE_OF_COLONY
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC
